# https://help.github.com/en/articles/metadata-syntax-for-github-actions

author: 'localheinz'

branding:
  icon: 'box'
  color: 'green'

name: 'composer-require-checker-action'

description: 'Run maglnet/composer-require-checker to ensure your PHP project does not use any unknown symbols'.

inputs:
  version:
    description: 'Version constraint for maglnet/composer-require-checker'
    required: false
    default: '^2.0.0'

runs:
  using: 'docker'
  image: 'docker://localheinz/composer-require-checker-action'

