# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "**"

name: "Continuous Integration"

jobs:
  build:
    name: "Build"

    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: localheinz/composer-require-checker-action

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2.0.0

      - name: "Build Docker image"
        run: $(which docker) build --tag ${DOCKER_IMAGE}:latest .

      - name: "Cache dependencies installed with composer"
        uses: actions/cache@v1.0.3
        with:
          path: ~/.composer/cache
          key: php7.3-composer-${{ matrix.dependencies }}-${{ hashFiles('**/.build/composer.lock') }}
          restore-keys: |
            php7.3-composer-${{ matrix.dependencies }}-

      - name: "Install dependencies with composer"
        run: php7.3 $(which composer) install --working-dir=.build

      - name: "Run Docker image"
        run: $(which docker) run --interactive --rm --workdir=/app --volume ${GITHUB_WORKSPACE}/.build:/app ${DOCKER_IMAGE}:latest
